[package]
name = "mccm"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-files = "0.6"
maud = { version = "0.27.0", features = ["actix-web"] }
bollard = "0.19.4"
serde = { version = "1", features = ["derive"] }
